In [29]:
import pandas as pd
import numpy as np
from multipledispatch import dispatch 

def load_and_process(url_or_path_to_csv_file):

    # Method Chain 1 (Load data and deal with missing data)

    df1 = (
        pd.DataFrame(
            pd.read_csv("../../data/raw/understat.com.csv")
        )
    )
    # Method Chain 2 (Create new columns, drop others, and do processing)

    df2 = (
        df1
        .drop(
            columns = ['wins', 'draws', 'loses','scored', 'missed','npxG', 'xG_diff', 'xGA_diff', 'npxGA', 'npxGD', 'xpts', 'xpts_diff']
        )
        .rename(
            columns={'Unnamed: 0': 'League', 'Unnamed: 1':'Year'}
        )
        .set_index(
            'League'
        )
        .drop(
            'RFPL'
        )
        .reset_index()
    )

    # Make sure to return the latest dataframe

    return df2

@dispatch(str, int)
def data_filter(league, pos):
    df1 = load_and_process("../../data/raw/understat.com.csv")
    df2 = (
        df1[df1["League"]==league]
        )
    df3 = df2[df2['position']==pos]
    
    return df3

@dispatch(int)
def data_filter(pos):
    df1 = load_and_process("../../data/raw/understat.com.csv")
    df2 = df1[df1['position']==pos]
    
    return df2

@dispatch(str)
def data_filter(league):
    df1 = load_and_process("../../data/raw/understat.com.csv")
    df2 = (
        df1[df1["League"]==league]
        )
    
    return df2


    
load_and_process("../../data/raw/understat.com.csv")
data_filter(1)

,League,Year,position,team,matches,pts,xG,xGA,ppda_coef,oppda_coef,deep,deep_allowed
0,La_liga,2014,1,Barcelona,38,94,102.980152,28.444293,5.683535,16.367593,489,114
20,La_liga,2015,1,Barcelona,38,91,113.598270,34.029090,6.012152,15.064390,570,163
40,La_liga,2016,1,Real Madrid,38,93,90.866410,36.862559,9.742439,13.407533,333,173
60,La_liga,2017,1,Barcelona,38,93,90.486752,41.620820,9.109883,13.939373,528,188
80,La_liga,2018,1,Barcelona,38,87,83.279534,44.930950,9.015264,16.404885,417,171
100,La_liga,2019,1,Real Madrid,38,87,72.157218,33.146266,9.262202,14.476897,334,127
120,EPL,2014,1,Chelsea,38,87,68.643320,31.524344,10.942027,13.419520,407,171
140,EPL,2015,1,Leicester,38,81,68.416034,45.019954,10.099471,8.602384,217,275
160,EPL,2016,1,Chelsea,38,93,61.796887,28.618919,11.768276,11.874986,435,150
180,EPL,2017,1,Manchester City,38,100,91.434145,24.511918,6.707812,28.897068,541,96
200,EPL,2018,1,Manchester City,38,98,93.720559,25.732604,8.526164,30.468113,582,135
220,EPL,2019,1,Liverpool,38,99,75.193370,39.572898,8.607605,24.738212,429,145
240,Bundesliga,2014,1,Bayern Munich,34,79,66.205745,21.938729,5.761476,25.022717,388,83
258,Bundesliga,2015,1,Bayern Munich,34,88,77.041497,20.794377,6.563205,23.119249,353,103
276,Bundesliga,2016,1,Bayern Munich,34,82,73.908589,27.042341,6.467688,21.219964,433,133
294,Bundesliga,2017,1,Bayern Munich,34,84,76.548905,30.637835,8.482019,22.416087,375,117
312,Bundesliga,2018,1,Bayern Munich,34,78,92.240857,27.412344,8.642573,30.236541,435,89
330,Bundesliga,2019,1,Bayern Munich,34,82,92.851562,36.471658,8.064508,21.020124,407,119
348,Serie_A,2014,1,Juventus,38,87,59.077044,29.129634,8.715008,13.017563,334,152
368,Serie_A,2015,1,Juventus,38,91,62.989649,22.998835,8.919363,10.944932,270,101
388,Serie_A,2016,1,Juventus,38,91,68.736204,23.597126,9.497838,13.003989,302,117
408,Serie_A,2017,1,Juventus,38,95,59.228735,28.577357,11.534032,15.573204,260,136
428,Serie_A,2018,1,Juventus,38,90,64.527180,35.032053,10.160174,13.964741,290,158
448,Serie_A,2019,1,Juventus,38,83,73.774528,40.996703,9.041600,15.611712,270,174
468,Ligue_1,2014,1,Paris Saint Germain,38,83,78.419930,28.240364,7.133794,16.841499,321,116
488,Ligue_1,2015,1,Paris Saint Germain,38,96,86.200951,24.365492,6.688799,20.325039,341,121
508,Ligue_1,2016,1,Monaco,38,95,76.036980,34.893628,9.587803,12.331291,226,139
528,Ligue_1,2017,1,Paris Saint Germain,38,93,89.924296,32.096711,8.232707,17.294541,478,118
548,Ligue_1,2018,1,Paris Saint Germain,38,91,95.344060,36.782405,7.785468,18.947672,459,132
568,Ligue_1,2019,1,Paris Saint Germain,27,68,76.419055,22.434996,7.460972,21.270465,324,100